name = "EduMaterialModels"
uuid = "dc10c695-e18c-49e2-887a-ef9f22cfa888"
authors = ["Knut Andreas Meyer and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
